// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89,…

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const terms = [1, 2];
let futureTerm = 0;
let i = 1;

while(futureTerm < 4000000){
  futureTerm = terms[i - 1] + terms[i];
  terms.push(futureTerm);
  i++;
}

const addTheTerms = (sum, currentTerm) => {
  sum += currentTerm;
  return sum;
};

const isEven = (x) => x % 2 === 0;

console.log(
  terms
    .filter(isEven)
    .reduce(addTheTerms),
);
